name: CI

on:
  push:
    branches:
      - '*'

jobs:
  client-github-url:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Setup venv
      run: |
        cd clients/client-github-url
        make setup-venv
    - name: Run unit test
      run: |
        cd clients/client-github-url
        source venv/bin/activate
        make unit-test
    - name: Run integration test
      run: |
        cd clients/client-github-url
        source venv/bin/activate
        make integration-test
